base_app/urls.py
from django.urls import path
from . import views

app_name = 'base_app'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name = 'about'),
    path('cost_calculator/', views.calc, name ='calc'),
    path('contact/', views.contact, name = 'contact'),
    path('car_fleet/', views.car_fleet, name = 'car_fleet'),
    ]

transport_company/urls.py
from django.contrib import admin
from django.urls import path, include
from base_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base_app/', include('base_app.urls')),
    path('', views.index, name='index'),
]

base_app/models.py
from django.db import models

# Create your models here.

base_app/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50, widget= forms.TextInput(attrs={'placeholder':'Your name'}))
    email_address = forms.EmailField(max_length = 150, widget= forms.EmailInput(attrs={'placeholder':'email@example.com'}))
    message = forms.CharField(widget = forms.Textarea(attrs={'placeholder':'Your message goes here'}), max_length = 2000)

base_app/views.py
from django.conf import settings
from django.core.mail import send_mail,BadHeaderError
from django.shortcuts import render
from .forms import ContactForm
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'base_app/index.html')

def about(request):
    return render(request,'base_app/about.html')

def calc(request):
    return render(request,'base_app/calc.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "New Contact Message"
            body = {
            'name': form.cleaned_data['name'],
            'email': form.cleaned_data['email_address'],
            'message': form.cleaned_data['message'],}
            message= '\n'.join(body.values())
            thank= True

            try:
                send_mail(subject, message, 'hotarubiq@gmail.com',['hotarubiq@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return render(request, "base_app/contact.html")

    form = ContactForm
    context={'form':form}
    return render (request, "base_app/contact.html", context)


def car_fleet(request):
    return render(request,'base_app/car_fleet.html')

templates/base_app/about.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load static %}
{% block body_block %}

<title>About</title>

<body>


  <main>

    <section class="main-container top-container">
      <h2 class=' header mx-3'>WHO ARE WE?</h2>
      <div class=" left-side">
        <img class="photo img-fluid" src="{% static 'images/about-photo.jpg' %}" alt="Man driving a bus">
      </div>
      <div class=" right-side  ">
        <p>This is not a real company, but a fake name created for portolio reasons. Althought if it was, the story
          about how it came to be could be something like that:</p>
        <p>It all began in 1980 with one old bus and a dream. The owner, Anton S., built it all from the scratch,
          working tirereslly and saving for a next vehicle.</p>
        <p>The company grew, Anton hired more drivers, bought more buses and moved the center of their operations to
          Wonderville. </p>
        <p>Nowadays Anton Transpo is well known locally as their buses takes children to schools, workers to workplaces
          and travelers of all kinds to their chosen destinations.</p>
        <p>Anton Transpo organizes travels also to other UE countries, mostly to vacation or summer work destinations.
        </p>
      </div>




    </section>

  </main>

</body>


{% endblock %}

templates/base_app/base.html
<!DOCTYPE html>
{% load static %}

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
    integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet" media="all">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">


  <title>Home</title>
  <style>
    .busbackground-image {
      background-image: url({%static 'images/b3.jpg'%});
    }

    .main-container {
      background-image: url({%static '/images/back2.jpg'%});
    }
  </style>
</head>
<html>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'base_app:index' %}"><img src="{% static 'images/logo.png' %}"
        alt="Anton Transpo Logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base_app:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base_app:car_fleet' %}">Car Fleet</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base_app:calc' %}">Calculator</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base_app:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </nav>




  {% block body_block %}
  {% endblock %}
  <footer class="fixed-bottom">
    <div class="d-none d-sm-block">
      <script>document.write(new Date().getFullYear());</script>, Copyright Anton Transpo, Logo by <a
        href="https://www.designevo.com/" title="Free Online Logo Maker" id="logoLink">Designenvo</a>
    </div>

    <div><a href="https://github.com/dominikapap"><i class="fa-brands fa-github fa-2xl" "></i></a>
      <a href=" https://www.linkedin.com/in/dominika-papierska/"><i class="fa-brands fa-linkedin fa-2xl"></i></a>
      <a href="mailto:domi.papierska@gmail.com" id="mail"><i class="fa-solid fa-envelope fa-2xl"></i></a>
    </div>

  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/my_script.js' %}"></script>
</body>



</html>

templates/base_app/calc.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load static %}
{% block body_block %}

<title>CALCULATOR</title>

<style>
  .main-container {
    background-image: url({%static 'images/back2.jpg'%});
  }
</style>



<body>
  <main>
    <section class="main-container top-container">
      <h2 class="header mx-3 "> RIDE COST CALCULATOR</h2>

      <div class="row">
        <div class="col-xl calc-left-side ">
          <img class="img-fluid photo mx-3" src="{% static 'images/calc.jpg' %}" alt="man using a caculator">
        </div>

        <div class="col-xl right-side-calc ">


          <p class="calc-info pt-3">Check approximate cost of booking a ride </p>


          <div class="form-container">

            <form id="costform" onsubmit="return false;">

              <div class="form-group">
                <label class='kms-label' for="kms">Journey length: </label>
                <input type="number" placeholder='kms' name="kms" id="kms" min="0" maxlength="6" size='6'
                  onchange="calculateTotal()" />
              </div>
              <div>

                <label class="cartype-label">Select Bus Type:</label>

                <select id="cartype" name='cartype' onchange="calculateTotal()">
                  <option value="None">-</option>
                  <option value="Neoplan Tourliner">Neoplan Tourliner</option>
                  <option value="Volvo">Volvo</option>
                  <option value="School Bus">School Bus</option>
                  <option value="Small White Bus">Small White Bus</option>
                  <option value="Neoplan Cityliner VIP"> Cityliner VIP</option>
                </select>
              </div>

              <div>

                <label class="fee-label">Additional Fee: </label>

                <select id="selectedfee" name='selectedfee' onchange="calculateTotal()">
                  <option value="Selectfee">-</option>
                  <option value="Small">Small - 50P LN</option>
                  <option value="Medium">Medium - 150 PLN</option>
                  <option value="Large">Large - 300 PLN</option>
                </select>
              </div>




              <div class="form-check-reverse ">
                <label class="form-check-label" for='includebuffer' class="inlinelabel">Include buffer of 10%?</label>
                <input class="form-check-input " type="checkbox" id="includebuffer" name='includebuffer'
                  onclick="calculateTotal()" />
              </div>



              <div class="font-weight-bold display-4 " id="total">Total Price is: <span id="totalPrice"></span></div>


            </form>
          </div>
        </div>
      </div>
    </section>
  </main>
</body>

<script type="text/javascript" src="{% static " js/my_script.js" %}"></script>

{% endblock %}

templates/base_app/car_fleet.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load static %}
{% block body_block %}

<title>CAR FLEET</title>

<body>
    <main>
        <section class="main-container top-container ">


            <h2 class="header mb-5  mx-3">CHECK OUT OUR AWESOME FLEET</h2>


            <div class="carousel-col left-side">
                <div id="carouselIndicators" class="carousel slide carousel-fade" data-ride="carousel">

                    <div class="carousel-inner">

                        <div class="carousel-item active">
                            <img class="d-block w-100" src="{% static 'images/cardbus1.jpg' %}" alt="Neoplan">
                            <div class="carousel-caption d-none d-md-block">
                                <h1 class='display-3'>NEOPLAN TOURLINER</h1>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <img class="d-block w-100" src="{% static 'images/cardbus2.jpg' %}" alt="Setra">
                            <div class="carousel-caption d-none d-md-block">
                                <h1 class='display-3'>SETRA</h1>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <img class="d-block w-100" src="{% static 'images/cardbus3.jpg' %}" alt="Volvo bus">
                            <div class="carousel-caption d-none d-md-block">
                                <h1 class='display-3'>VOLVO</h1>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <img class="d-block w-100" src="{% static 'images/cardbus4.jpg' %}" alt="School Buss">
                            <div class="carousel-caption d-none d-md-block">
                                <h1 class='display-3'>SCHOOL BUS</h1>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <img class="d-block w-100" src="{% static 'images/cardbus5.jpg' %}" alt="Small White Bus">
                            <div class="carousel-caption d-none d-md-block">
                                <h1 class='display-3'>SMALL WHITE BUS</h>
                            </div>
                        </div>
                    </div>

                    <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>

                    <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <div class=" right-side">
                <p>We have many different buses to accomodate different needs. We have big luxurious buses and small
                    ones (but still very comfortable) as well.</p>
                <p>They have WIFI and air conditioning, TV, minibar and minifridge. They will take you for a magical
                    journey to your chosen destination. Lorem ipsum dolor sit amet consectetur.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat.</p>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                    totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
                    dicta sunt explicabo.</p>
            </div>


        </section>

    </main>
</body>


{% endblock %}

templates/base_app/contact.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load static %}
{% block body_block %}

<title>CONTACT</title>

<body>

  <main>
    <section class="main-container top-container">
      <h2 class="text-center mx-3 header mb-5">CONTACT PAGE</h2>
      <div class="contact-container">

        <div class=" mb-5 contact-photo ">
          <img class='photo img-fluid  ' src="{% static 'images/contact.jpg' %}" alt="yellow bus toy">
        </div>

        <div class=" contact-form-container ">

          {% if username %}
          <p class='display-4 thankyou'> Thank you, {{username}}</p>
          <p class='display-5 thankyou'>We received your message and will contact you back shortly</p>

          {% else %}
          <p class="contact-form-text">To contact us please fill out this form. Contact info can be also found below</p>

          <form method="POST" class='label-forms '>
            {% csrf_token %}
            <div class='row'>
              <div class='col-md'>

                <label class="mx-md-3" for='id_name'>Name:</label>
                <div class="mx-md-3">{{form.name}}</div>
              </div>
              <div class='col-md'>
                <label class="mx-md-3" for='id_email'>Email:</label>
                <div class="mx-md-3">{{form.email_address}}</div>
              </div>
            </div>

            <label class="mx-md-3 mt-2" for"id_message">Message</label>
            <div class="mx-md-3">{{form.message}}</div>

            <button class="btn btn-outline-light  button-form m-3 " type="submit">SEND<i
                class="far fa-envelope p-2"></i></button>
          </form>
          {% endif %}
        </div>

      </div>



      <div class="row contact-second-row">
        <div class="col-lg contact-info  ">
          <h2 class="contact-info-header"><span class="contact-info-header-span">You can find us here:</span></h2>
          <p class='pt-3'><i class="fas fa-map-marker-alt mx-2"></i>Adress:</p>
          <p>Not Real Street 12/34</p>
          <p>00-000 Warsaw</p>
          <p class='mb-5'>Poland</p>
          <h2 class="contact-info-header"><span class="contact-info-header-span">Contact us:</span></h2>
          <p class='pt-3'><a href="tel:123-456-7890" data-toggle="tooltip" data-placement="top"
              title="Please don't call this number"><i class="fas fa-phone p-2"></i>123-456-7890</a></p>
          <p data-toggle="tooltip" data-placement="right" title="Not an actual email address"><a
              href="mailto:domi.papierska@gmail.com"><i class="far fa-envelope p-2"></i>lorem@ipsum.com</a></p>
        </div>

        <div class="col-lg d-none d-md-block google-map map-responsive ">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d156388.35438654714!2d20.921113966387182!3d52.233065320451125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc669a869f01%3A0x72f0be2a88ead3fc!2sWarszawa!5e0!3m2!1spl!2spl!4v1643382110211!5m2!1spl!2spl"
            width="1000" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>

        <div class="col d-md-none google-map ">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d156388.35438654714!2d20.921113966387182!3d52.233065320451125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc669a869f01%3A0x72f0be2a88ead3fc!2sWarszawa!5e0!3m2!1spl!2spl!4v1643382110211!5m2!1spl!2spl"
            width="340" height="240" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>

      </div>
      </div>

    </section>


  </main>



</body>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
{% endblock %}

templates/base_app/index.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load static %}
{% block body_block %}

<title>Home</title>

<style>
  .busbackground-image {
    background-image: url({%static 'images/b3.jpg'%});
  }
</style>
<main>
  <section>
    <div class="busbackground-image">
      <div class="main-text">
        <h1 class="company-title ">Anton Transpo</h1>
        <p class="company-slogan">Ride with Us</p>
        <!--<p class="bus"><i class="fa-solid fa-van-shuttle fa-5x"></i></p>-->
      </div>
    </div>
  </section>
  <section class="main-container text-white">
    <h2 class=' header mx-3'>WHO ARE WE?</h2>
    <div class=" left-side">
      <img class="photo img-fluid" src="{% static 'images/about-photo.jpg' %}" alt="Man driving a bus">
    </div>
    <div class=" right-side  ">
      <p>This is not a real company, but a fake name created for portolio reasons. Althought if it was, the story about
        how it came to be could be something like that:</p>
      <p>It all began in 1980 with one old bus and a dream. The owner, Anton S., built it all from the scratch, working
        tirereslly and saving for a next vehicle.</p>
      <p>The company grew, Anton hired more drivers, bought more buses and moved the center of their operations to
        Wonderville. </p>
      <p>Nowadays Anton Transpo is well known locally as their buses takes children to schools, workers to workplaces
        and travelers of all kinds to their chosen destinations.</p>
      <p>Anton Transpo organizes travels also to other UE countries, mostly to vacation or summer work destinations.</p>
    </div>




  </section>
  <section class="main-container ">
    <h2 class="header mb-5  mx-3">CHECK OUT OUR AWESOME FLEET</h2>
    <div class="left-side" id="carousel-col">
      <div id="carouselIndicators" class="carousel slide carousel-fade" data-ride="carousel">

        <div class="carousel-inner">

          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'images/cardbus1.jpg' %}" alt="Neoplan">
            <div class="carousel-caption d-none d-md-block">
              <h1 class='display-3'>NEOPLAN TOURLINER</h1>
            </div>
          </div>

          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/cardbus2.jpg' %}" alt="Setra">
            <div class="carousel-caption d-none d-md-block">
              <h1 class='display-3'>SETRA</h1>
            </div>
          </div>

          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/cardbus3.jpg' %}" alt="Volvo bus">
            <div class="carousel-caption d-none d-md-block">
              <h1 class='display-3'>VOLVO</h1>
            </div>
          </div>

          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/cardbus4.jpg' %}" alt="School Buss">
            <div class="carousel-caption d-none d-md-block">
              <h1 class='display-3'>SCHOOL BUS</h1>
            </div>
          </div>

          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/cardbus5.jpg' %}" alt="Small White Bus">
            <div class="carousel-caption d-none d-md-block">
              <h1 class='display-3'>SMALL WHITE BUS</h>
            </div>
          </div>
        </div>

        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class=" right-side">
      <p>We have many different buses to accomodate different needs. We have big luxurious buses and small ones (but
        still very comfortable) as well.</p>
      <p>They have WIFI and air conditioning, TV, minibar and minifridge. They will take you for a magical journey to
        your chosen destination. Lorem ipsum dolor sit amet consectetur.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat.</p>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
        aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    </div>


  </section>
  <section class="main-container">
    <h2 class="header mx-3 "> RIDE COST CALCULATOR</h2>

    <div class="row">
      <div class="col-xl calc-left-side ">
        <img class="img-fluid photo mx-3" src="{% static 'images/calc.jpg' %}" alt="man using a caculator">
      </div>

      <div class="col-xl right-side-calc ">


        <p class="calc-info pt-3">Check approximate cost of booking a ride </p>


        <div class="form-container">

          <form id="costform" onsubmit="return false;">

            <div class="form-group">
              <label class='kms-label' for="kms">Journey length: </label>
              <input type="number" placeholder='kms' name="kms" id="kms" min="0" maxlength="6" size='6'
                onchange="calculateTotal()" />
            </div>
            <div>

              <label class="cartype-label">Select Bus Type:</label>

              <select id="cartype" name='cartype' onchange="calculateTotal()">
                <option value="None">-</option>
                <option value="Neoplan Tourliner">Neoplan Tourliner</option>
                <option value="Volvo">Volvo</option>
                <option value="School Bus">School Bus</option>
                <option value="Small White Bus">Small White Bus</option>
                <option value="Neoplan Cityliner VIP"> Cityliner VIP</option>
              </select>
            </div>

            <div>

              <label class="fee-label">Additional Fee: </label>

              <select id="selectedfee" name='selectedfee' onchange="calculateTotal()">
                <option value="Selectfee">-</option>
                <option value="Small">Small - 50P LN</option>
                <option value="Medium">Medium - 150 PLN</option>
                <option value="Large">Large - 300 PLN</option>
              </select>
            </div>




            <div class="form-check-reverse ">
              <label class="form-check-label" for='includebuffer' class="inlinelabel">Include buffer of 10%?</label>
              <input class="form-check-input " type="checkbox" id="includebuffer" name='includebuffer'
                onclick="calculateTotal()" />
            </div>



            <div class="font-weight-bold display-4 " id="total">Total Price is: <span id="totalPrice"></span></div>


          </form>
        </div>
      </div>
    </div>
  </section>
  <section class="main-container top-container">
    <h2 class="text-center mx-3 header mb-5">CONTACT PAGE</h2>



    <div class="row contact-second-row">
      <div class="col-lg contact-info  ">
        <h2 class="contact-info-header"><span class="contact-info-header-span">You can find us here:</span></h2>
        <p class='pt-3'><i class="fas fa-map-marker-alt mx-2"></i>Adress:</p>
        <p>Not Real Street 12/34</p>
        <p>00-000 Warsaw</p>
        <p class='mb-5'>Poland</p>
        <h2 class="contact-info-header"><span class="contact-info-header-span">Contact us:</span></h2>
        <p class='pt-3'><a href="tel:123-456-7890" data-toggle="tooltip" data-placement="top"
            title="Please don't call this number"><i class="fas fa-phone p-2"></i>123-456-7890</a></p>
        <p data-toggle="tooltip" data-placement="right" title="Not an actual email address"><a
            href="mailto:domi.papierska@gmail.com"><i class="far fa-envelope p-2"></i>lorem@ipsum.com</a></p>
        <p>You can also send us a message <a href="{% url 'base_app:contact' %}">HERE</a></p>
      </div>

      <div class="col-lg d-none d-md-block google-map map-responsive ">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d156388.35438654714!2d20.921113966387182!3d52.233065320451125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc669a869f01%3A0x72f0be2a88ead3fc!2sWarszawa!5e0!3m2!1spl!2spl!4v1643382110211!5m2!1spl!2spl"
          width="1000" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      </div>

      <div class="col d-md-none google-map ">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d156388.35438654714!2d20.921113966387182!3d52.233065320451125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc669a869f01%3A0x72f0be2a88ead3fc!2sWarszawa!5e0!3m2!1spl!2spl!4v1643382110211!5m2!1spl!2spl"
          width="340" height="240" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      </div>

    </div>
    </div>
  </section>

</main>



{% endblock %}